// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package plus.jdk.websocket.protoc;

public interface WsMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:plus.jdk.websocket.protoc.WsMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string uid = 1;</code>
   * @return Whether the uid field is set.
   */
  boolean hasUid();
  /**
   * <code>optional string uid = 1;</code>
   * @return The uid.
   */
  java.lang.String getUid();
  /**
   * <code>optional string uid = 1;</code>
   * @return The bytes for uid.
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>optional string path = 2;</code>
   * @return Whether the path field is set.
   */
  boolean hasPath();
  /**
   * <code>optional string path = 2;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>optional string path = 2;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>optional bytes data = 3;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>optional bytes data = 3;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>optional .plus.jdk.websocket.protoc.MessageType type = 4;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>optional .plus.jdk.websocket.protoc.MessageType type = 4;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>optional .plus.jdk.websocket.protoc.MessageType type = 4;</code>
   * @return The type.
   */
  plus.jdk.websocket.protoc.MessageType getType();
}
